### ISSUE TITLE
docs down

### ISSUE THREAD

**Issue by Sixtease** [ella/ella#98] opened 2012-05-30 10:08 UTC
http://ella.rtfd.org/ gives a 403, the link to quickstart gives a 404

**Comment by xaralis** [comment] 2012-05-30 11:27
Problem is probably caused by the fact that tests are not installed together with the package when using `python setup.py install` which is what readthedocs.org does. Our sphinx configuration file needs this because it uses `test_ella` project to allow for autodoc module to work properly. 

``` python
import ella
from test_ella import settings

setup_environ(settings)
```

I am not sure about apropriate solution at the moment. I understand that including tests with `setup.py install` is not a nice way to overcome the problem, but I can't think of anything else :(

**Comment by honzakral** [comment] 2012-05-30 13:58
fixed in https://github.com/ella/ella/commit/138d0b7f7709ab8d1a413a5b2c60deba6466cd9d

**Closed as completed by honzakral** 2012-05-30 13:58 UTC
Labels: asap, docs
