### ISSUE TITLE
Newman's responses are shown out of newman app

### ISSUE THREAD

**Issue by jezradek** [ella/ella#72] opened 2012-02-13 10:49 UTC
If you add or edit some object e.g. article or photo via newman. A response for this action is shown on your website. The response is gone after refresh.

See:
http://uloz.to/xcycL8b/response-out-newman-png

**Comment by xaralis** [comment] 2012-02-14 08:57
This is nothing serious: https://docs.djangoproject.com/en/dev/ref/contrib/messages/#behavior-of-parallel-requests.

Most likely, it is caused by newman not pulling the created messages like here: https://docs.djangoproject.com/en/dev/ref/contrib/messages/#displaying-messages.

**Comment by jezradek** [comment] 2012-02-14 10:00
I agree and just wanted you to know.

**Comment by xaralis** [comment] 2012-02-22 12:39
This is easily solved by proper configuration and I am therfore closing this.

FYI, you need to ensure the session is not shared by admin and client side of installation. For example, this can be done by using `SESSION_COOKIE_DOMAIN` setting.

**Closed as completed by xaralis** 2012-02-22 12:39 UTC
Labels: django-1.3

**Comment by whit** [comment] 2012-02-22 12:57
You need same session for editors to allow preview non published articles on frontend... But keep it closed, it's a small thing.

**Comment by xaralis** [comment] 2012-02-22 12:59
Ah, you're right, I forgot. Shame on me.
