### ISSUE TITLE
Newman's error when "save and continue editing" new photo

### ISSUE THREAD

**Issue by jezradek** [ella/ella#73] opened 2012-02-13 18:40 UTC
You got newman's error when "save and continue editing"(uložit a pokračovat v úpravách) new photo. It appears at first time you try to add new photo by "save and continue editing" button. New photo is saved, unfortunately you can't continue editing it.
Newman's response is: can't continue editing(Object ID was not accepted) see link below.

See:
http://uloz.to/x7JqQWE/photo-save-continue-png

**Comment by Sixtease** [comment] 2012-02-13 20:55
I propose we replace the flash solution with jQuery file uploader that we're incorporating to mass upload to achieve more consistence. Maybe we could even join "add photo" with "mass upload" whatsoever.

**Comment by xaralis** [comment] 2012-02-14 08:53
This is gonna be hard to achieve since writer use the flash editor quite often and it would be major regression for them to let it go.

**Comment by xaralis** [comment] 2012-02-22 11:35
Removing "asap" label, this error is present from the very born of newman and probably won't be fixed in any near future.

**Comment by honzakral** [comment] 2012-03-17 15:04
closing as newman has become it's own project: https://github.com/ella/django-newman

**Closed as completed by honzakral** 2012-03-17 15:04 UTC
Labels: nice-to-have, newman
